//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Comments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Name { get; set; }
        [DisplayName("Contact Email")]
        public string ContactEmail { get; set; }
        [DisplayName("Please Contact")]
        public bool PleaseContact { get; set; }
        [Required]
        [DisplayName("Originating Site")]
        public string OriginatingSite { get; set; }
        [Required]
        [DisplayName("Comment")]
        [DataType(DataType.MultilineText)]
        public string Comment1 { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
    }
}
